<div class="alert alert-info ce-page-header">
    <div class="alert-header">
        <?php echo $this->user->lang("Affiliate")." ".$this->user->lang("Settings")." - ".$this->user->lang("Custom Links"); ?>
    </div>
    <p class="alert-content">
        <?php echo $this->user->lang('To track affiliate hits on your website, paste the code below on every page you’d like to track. Your Clientexec installation automatically tracks hits.'); ?>

    </p>
</div>
<pre>
<?php echo $this->html; ?>
</pre>