<html>
<table width="98%" cellpadding="0" cellspacing="0" border="0" align="center">
    <tr>
        <td>
            <?php foreach ($this->fields as $field) {
                if (is_array($field['fieldValue'])) {
                    echo $field['fieldName'].": ".str_replace(array('  '), array('&nbsp;'), nl2br($this->escape(print_r($field['fieldValue'], true))))."<br />";
                } else {
                    echo $field['fieldName'].": ".$this->escape($field['fieldValue'])."<br />";
                }
            } ?>
        </td>
    </tr>
</table>
</body>
</html>
