<style>
    .window-description .inputRow {
        margin-bottom: 10px;
    }
    .window-description .inputRow label {
        display: inline-block;
        vertical-align: middle;
        width: 142px;
    }
    .window-description .inputRow input {
        display: inline-block;
        vertical-align: middle;
        margin-bottom: 0;
    }

    .window-description .inputRow > div {
        width:  95%;
    }

    .window-description .inputRow .input-append input {
        width: 91.5%;
        border-radius: 4px
    }
    .window-description .inputRow input {
        width: 100%;
    }

</style>

<div class="inputRow">
    <label class="fieldlabel"><?php echo $this->user->lang("Amount");?></label>
    <div class="input-prepend input-append">
        <span class="add-on"><?php echo $this->currencyCode; ?></span>
        <input class="required" type="number" step="0.01" min="0" name="amount" placeholder="Amount" />
    </div>
</div>

<div class="inputRow">
    <label class="fieldlabel"><?php echo $this->user->lang("Description");?></label>
    <div>
        <input class="required" type="text" name="desc" placeholder="Description" />
    </div>
</div>