UPDATE `setting` SET `type` = '8' WHERE name='Ticket Number Prefix';

# ---------------------------------------------------------
# UPDATE BILLING EMAIL TEMPLATE TO WORK WITH BALANCE DUE AND PARTIAL PAYMENTS
# ----------------------------------------------------------
UPDATE `setting` SET `value`='Due Date: [DATE]\r\nInvoice #[INVOICENUMBER]\r\n\r\nATTN: [CLIENTNAME],\r\n\r\nYou currently have a balance of [BALANCEDUE] due on your account with [COMPANYNAME].  \r\n\r\nInvoice Description:\r\n[INVOICEDESCRIPTION]\r\n\r\nTotal Due: [AMOUNT]\r\nPaid: [PAID]\r\nBalance Due: [BALANCEDUE]\r\n\r\nPayment Instructions:\r\n1) Log into our client management site at [CLIENTAPPLICATIONURL] with your username and password\r\n2) Click on the \"Billing\" tab\r\n3) Select the invoice you want to pay\r\n4) Click on pay invoice\r\n\r\nWe greatly appreciate your efforts to ensure that payment\r\nis received in a timely matter.\r\n\r\nIf you have any questions regarding your account or if \r\nyou wish to pay by check, please feel free to contact us.\r\n\r\nNote: This email will serve as an official invoice for this payment.\r\n\r\n[COMPANYNAME]\r\n[BILLINGEMAIL]' WHERE `value`='Due Date: [DATE]\r\nInvoice #[INVOICENUMBER]\r\n\r\nATTN: [CLIENTNAME],\r\n\r\nYou currently have a balance of [AMOUNT] due on your account with [COMPANYNAME].  \r\n\r\nInvoice Description:\r\n[INVOICEDESCRIPTION]\r\n\r\nTotal Due: [AMOUNT]\r\n\r\nPayment Instructions:\r\n1) Log into our client management site at [CLIENTAPPLICATIONURL] with your username and password\r\n2) Click on the \"Billing\" tab\r\n3) Select the invoice you want to pay\r\n4) Click on pay invoice\r\n\r\nWe greatly appreciate your efforts to ensure that payment\r\nis received in a timely matter.\r\n\r\nIf you have any questions regarding your account or if \r\nyou wish to pay by check, please feel free to contact us.\r\n\r\nNote: This email will serve as an official invoice for this payment.\r\n\r\n[COMPANYNAME]\r\n[BILLINGEMAIL]';
UPDATE `setting` SET `value_alternate`='<HTML><head></head><body>Due Date: [DATE]<br />\r\nInvoice #[INVOICENUMBER]<br />\r\n<br />\r\nATTN: [CLIENTNAME],<br />\r\n<br />\r\nYou currently have a balance of [BALANCEDUE] due on your account with [COMPANYNAME].  <br />\r\n<br />\r\nInvoice Description:<br />\r\n[INVOICEDESCRIPTION]<br />\r\n<br />\r\nTotal Due: [AMOUNT]<br />\r\nPaid: [PAID]<br />\r\nBalance Due: [BALANCEDUE]<br />\r\n<br />\r\nPayment Instructions:<br />\r\n1) Log into our client management site at [CLIENTAPPLICATIONURL] with your username and password<br />\r\n2) Click on the \"Billing\" tab<br />\r\n3) Select the invoice you want to pay<br />\r\n4) Click on pay invoice<br />\r\n<br />\r\nWe greatly appreciate your efforts to ensure that payment<br />\r\nis received in a timely matter.<br />\r\n<br />\r\nIf you have any questions regarding your account or if <br />\r\nyou wish to pay by check, please feel free to contact us.<br />\r\n<br />\r\nNote: This email will serve as an official invoice for this payment.<br />\r\n<br />\r\n[COMPANYNAME]<br />\r\n[BILLINGEMAIL]</body></HTML>' WHERE `value_alternate`='<HTML><head></head><body>Due Date: [DATE]<br />\r\nInvoice #[INVOICENUMBER]<br />\r\n<br />\r\nATTN: [CLIENTNAME],<br />\r\n<br />\r\nYou currently have a balance of [AMOUNT] due on your account with [COMPANYNAME].  <br />\r\n<br />\r\nInvoice Description:<br />\r\n[INVOICEDESCRIPTION]<br />\r\n<br />\r\nTotal Due: [AMOUNT]<br />\r\n<br />\r\nPayment Instructions:<br />\r\n1) Log into our client management site at [CLIENTAPPLICATIONURL] with your username and password<br />\r\n2) Click on the \"Billing\" tab<br />\r\n3) Select the invoice you want to pay<br />\r\n4) Click on pay invoice<br />\r\n<br />\r\nWe greatly appreciate your efforts to ensure that payment<br />\r\nis received in a timely matter.<br />\r\n<br />\r\nIf you have any questions regarding your account or if <br />\r\nyou wish to pay by check, please feel free to contact us.<br />\r\n<br />\r\nNote: This email will serve as an official invoice for this payment.<br />\r\n<br />\r\n[COMPANYNAME]<br />\r\n[BILLINGEMAIL]</body></HTML>';
UPDATE `setting` SET `value`='Dear [CLIENTNAME],\r\n\r\nPayment was rejected for Invoice #[INVOICENUMBER], sent on [DATE].\r\n\r\nYou currently have a balance of [BALANCEDUE] due on your account with [COMPANYNAME].  \r\n\r\nInvoice Description:\r\n[INVOICEDESCRIPTION]\r\n\r\nTotal Due: [AMOUNT]\r\nPaid: [PAID]\r\nBalance Due: [BALANCEDUE]\r\n\r\nPayment Instructions:\r\n1) Log into our client management site at [CLIENTAPPLICATIONURL] with your username and password\r\n2) Click on the \"Billing\" tab\r\n3) Select the invoice you want to pay\r\n4) Click on pay invoice\r\n\r\nWe greatly appreciate your efforts to ensure that payment\r\nis received in a timely matter.\r\n\r\nIf you have any questions regarding your account or if \r\nyou wish to pay by check, please feel free to contact us.\r\n\r\nNote: This email will serve as an official invoice for this payment.\r\n\r\n[COMPANYNAME]\r\n[BILLINGEMAIL]' WHERE `value`='Dear [CLIENTNAME],\r\n\r\nPayment was rejected for Invoice #[INVOICENUMBER], sent on [DATE].\r\n\r\nYou currently have a balance of [AMOUNT] due on your account with [COMPANYNAME].  \r\n\r\nInvoice Description:\r\n[INVOICEDESCRIPTION]\r\n\r\nTotal Due: [AMOUNT]\r\n\r\nPayment Instructions:\r\n1) Log into our client management site at [CLIENTAPPLICATIONURL] with your username and password\r\n2) Click on the \"Billing\" tab\r\n3) Select the invoice you want to pay\r\n4) Click on pay invoice\r\n\r\nWe greatly appreciate your efforts to ensure that payment\r\nis received in a timely matter.\r\n\r\nIf you have any questions regarding your account or if \r\nyou wish to pay by check, please feel free to contact us.\r\n\r\nNote: This email will serve as an official invoice for this payment.\r\n\r\n[COMPANYNAME]\r\n[BILLINGEMAIL]';
UPDATE `setting` SET `value_alternate`='<HTML><head></head><body>Dear [CLIENTNAME],<br />\r\n<br />\r\nPayment was rejected for Invoice #[INVOICENUMBER], sent on [DATE].<br />\r\n<br />\r\nYou currently have a balance of [BALANCEDUE] due on your account with [COMPANYNAME].  <br />\r\n<br />\r\nInvoice Description:<br />\r\n[INVOICEDESCRIPTION]<br />\r\n<br />\r\nTotal Due: [AMOUNT]<br />\r\nPaid: [PAID]<br />\r\nBalance Due: [BALANCEDUE]<br />\r\n<br />\r\nPayment Instructions:<br />\r\n1) Log into our client management site at [CLIENTAPPLICATIONURL] with your username and password<br />\r\n2) Click on the \"Billing\" tab<br />\r\n3) Select the invoice you want to pay<br />\r\n4) Click on pay invoice<br />\r\n<br />\r\nWe greatly appreciate your efforts to ensure that payment<br />\r\nis received in a timely matter.<br />\r\n<br />\r\nIf you have any questions regarding your account or if <br />\r\nyou wish to pay by check, please feel free to contact us.<br />\r\n<br />\r\nNote: This email will serve as an official invoice for this payment.<br />\r\n<br />\r\n[COMPANYNAME]<br />\r\n[BILLINGEMAIL]</body></HTML>' WHERE `value_alternate`='<HTML><head></head><body>Dear [CLIENTNAME],<br />\r\n<br />\r\nPayment was rejected for Invoice #[INVOICENUMBER], sent on [DATE].<br />\r\n<br />\r\nYou currently have a balance of [AMOUNT] due on your account with [COMPANYNAME].  <br />\r\n<br />\r\nInvoice Description:<br />\r\n[INVOICEDESCRIPTION]<br />\r\n<br />\r\nTotal Due: [AMOUNT]<br />\r\n<br />\r\nPayment Instructions:<br />\r\n1) Log into our client management site at [CLIENTAPPLICATIONURL] with your username and password<br />\r\n2) Click on the \"Billing\" tab<br />\r\n3) Select the invoice you want to pay<br />\r\n4) Click on pay invoice<br />\r\n<br />\r\nWe greatly appreciate your efforts to ensure that payment<br />\r\nis received in a timely matter.<br />\r\n<br />\r\nIf you have any questions regarding your account or if <br />\r\nyou wish to pay by check, please feel free to contact us.<br />\r\n<br />\r\nNote: This email will serve as an official invoice for this payment.<br />\r\n<br />\r\n[COMPANYNAME]<br />\r\n[BILLINGEMAIL]</body></HTML>';
UPDATE `setting` SET `value`='Due Date: [DATE]\nInvoice #[INVOICENUMBER]\n\nATTN: [CLIENTNAME],\n\nYou currently have an overdue invoice of [BALANCEDUE] due on your account with [COMPANYNAME].\n\nInvoice Description:\n[INVOICEDESCRIPTION]\n\nTotal Due: [AMOUNT]\nPaid: [PAID]\nBalance Due: [BALANCEDUE]\n\nPayment Instructions:\n1) Log into our client management site at [CLIENTAPPLICATIONURL] with your username and password\n2) Click on the \"Billing\" tab\n3) Select the invoice you want to pay\n4) Click on pay invoice\n\nWe greatly appreciate your efforts to ensure that payment is received in a timely matter.\n\nIf you have any questions regarding your account or if you wish to pay by check, please feel free to contact us.\n\nNote: This E-mail will serve as an official invoice for this payment.\n\n[COMPANYNAME]\n[BILLINGEMAIL]' WHERE `value`='Due Date: [DATE]\nInvoice # [INVOICENUMBER]\n\nATTN: [CLIENTNAME],\n\nYou currently have an overdue invoice of [AMOUNT] due on your account with [COMPANYNAME].\n\nInvoice Description:\n[INVOICEDESCRIPTION]\nTotal Due: [AMOUNT]\n\nPayment Instructions:\n1) Log into our client management site at [CLIENTAPPLICATIONURL] with your username and password\n2) Click on the \"Billing\" tab\n3) Select the invoice you want to pay\n4) Click on pay invoice\n\nWe greatly appreciate your efforts to ensure that payment is received in a timely matter.\n\nIf you have any questions regarding your account or if you wish to pay by check, please feel free to contact us.\n\nNote: This E-mail will serve as an official invoice for this payment.\n\n[COMPANYNAME]\n[BILLINGEMAIL]';
UPDATE `setting` SET `value_alternate`='<HTML><head></head><body>Due Date: [DATE]<br />\nInvoice #[INVOICENUMBER]<br />\n<br />\nATTN: [CLIENTNAME],<br />\n<br />\nYou currently have an overdue invoice of [BALANCEDUE] due on your account with [COMPANYNAME].<br />\n<br />\nInvoice Description:<br />\n[INVOICEDESCRIPTION]<br />\n<br />\nTotal Due: [AMOUNT]<br />\nPaid: [PAID]<br />\nBalance Due: [BALANCEDUE]<br />\n<br />\nPayment Instructions:<br />\n1) Log into our client management site at [CLIENTAPPLICATIONURL] with your username and password<br />\n2) Click on the \"Billing\" tab<br />\n3) Select the invoice you want to pay<br />\n4) Click on pay invoice<br />\n<br />\nWe greatly appreciate your efforts to ensure that payment is received in a timely matter.<br />\n<br />\nIf you have any questions regarding your account or if you wish to pay by check, please feel free to contact us.<br />\n<br />\nNote: This E-mail will serve as an official invoice for this payment.<br />\n<br />\n[COMPANYNAME]<br />\n[BILLINGEMAIL]</body></HTML>' WHERE `value_alternate`='<HTML><head></head><body>Due Date: [DATE]<br />\nInvoice # [INVOICENUMBER]<br />\n<br />\nATTN: [CLIENTNAME],<br />\n<br />\nYou currently have an overdue invoice of [AMOUNT] due on your account with [COMPANYNAME].<br />\n<br />\nInvoice Description:<br />\n[INVOICEDESCRIPTION]<br />\nTotal Due: [AMOUNT]<br />\n<br />\nPayment Instructions:<br />\n1) Log into our client management site at [CLIENTAPPLICATIONURL] with your username and password<br />\n2) Click on the \"Billing\" tab<br />\n3) Select the invoice you want to pay<br />\n4) Click on pay invoice<br />\n<br />\nWe greatly appreciate your efforts to ensure that payment is received in a timely matter.<br />\n<br />\nIf you have any questions regarding your account or if you wish to pay by check, please feel free to contact us.<br />\n<br />\nNote: This E-mail will serve as an official invoice for this payment.<br />\n<br />\n[COMPANYNAME]<br />\n[BILLINGEMAIL]</body></HTML>';
UPDATE `setting` SET `value`='ATTN: [CLIENTNAME],\n\nYou have an upcoming invoice for [BALANCEDUE] on [DATE] that will be charged to your credit card on file with [COMPANYNAME].  If you do not approve of this charge and would like to cancel your subscription please contact us immediately.\n\nYou may review your invoice history at any time by logging in at: [CLIENTAPPLICATIONURL]\n\nIf you have any questions regarding your account, please feel free to contact us at [BILLINGEMAIL].\n\n\n[COMPANYNAME]\n[BILLINGEMAIL]' WHERE `value`='ATTN: [CLIENTNAME],\n\nYou have an upcoming invoice for [AMOUNT] on [DATE] that will be charged to your credit card on file with [COMPANYNAME].  If you do not approve of this charge and would like to cancel your subscription please contact us immediately.\n\nYou may review your invoice history at any time by logging in at: [CLIENTAPPLICATIONURL]\n\nIf you have any questions regarding your account, please feel free to contact us at [BILLINGEMAIL].\n\n\n[COMPANYNAME]\n[BILLINGEMAIL]';
UPDATE `setting` SET `value_alternate`='<HTML><head></head><body>ATTN: [CLIENTNAME],<br />\n<br />\nYou have an upcoming invoice for [BALANCEDUE] on [DATE] that will be charged to your credit card on file with [COMPANYNAME].  If you do not approve of this charge and would like to cancel your subscription please contact us immediately.<br />\n<br />\nYou may review your invoice history at any time by logging in at: [CLIENTAPPLICATIONURL]<br />\n<br />\nIf you have any questions regarding your account, please feel free to contact us at [BILLINGEMAIL].<br />\n<br />\n<br />\n[COMPANYNAME]<br />\n[BILLINGEMAIL]</body></HTML>' WHERE `value_alternate`='<HTML><head></head><body>ATTN: [CLIENTNAME],<br />\n<br />\nYou have an upcoming invoice for [AMOUNT] on [DATE] that will be charged to your credit card on file with [COMPANYNAME].  If you do not approve of this charge and would like to cancel your subscription please contact us immediately.<br />\n<br />\nYou may review your invoice history at any time by logging in at: [CLIENTAPPLICATIONURL]<br />\n<br />\nIf you have any questions regarding your account, please feel free to contact us at [BILLINGEMAIL].<br />\n<br />\n<br />\n[COMPANYNAME]<br />\n[BILLINGEMAIL]</body></HTML>';

# ---------------------------------------------------------
# THIS TABLE WILL BE USED FOR EMAIL TEMPLATES OF DIFFERENT TYPES
# ---------------------------------------------------------
ALTER TABLE `autoresponders` ADD `type` TINYINT( 4 ) NOT NULL DEFAULT '1' AFTER `id`;
ALTER TABLE `autoresponders` ADD `helpid` INT( 3 ) NOT NULL DEFAULT '0';
ALTER TABLE `autoresponders` ADD `description` TEXT;
ALTER TABLE `autoresponders` CHANGE `name` `name` VARCHAR( 75 ) NOT NULL;

# Add all the billing email setting to autoresponder
INSERT autoresponders (type,name,subject,contents,contents_html,helpid,description) SELECT 3, name, 'an', `value`, value_alternate,50,description FROM setting WHERE name = 'Invoice Template';
UPDATE autoresponders SET subject = 	( SELECT value FROM setting WHERE name='Invoice Template Subject') WHERE name='Invoice Template';
INSERT autoresponders (type,name,subject,contents,contents_html,helpid,description) SELECT 3, name, 'an', `value`, value_alternate,50,description FROM setting WHERE name = 'Payment Receipt Template';
UPDATE autoresponders SET subject = 	( SELECT value FROM setting WHERE name='Payment Receipt Subject Template') WHERE name='Payment Receipt Template';
INSERT autoresponders (type,name,subject,contents,contents_html,helpid,description) SELECT 3, name, 'an', `value`, value_alternate,50,description FROM setting WHERE name = 'Payment Rejected Template';
UPDATE autoresponders SET subject = 	( SELECT value FROM setting WHERE name='Payment Rejected Subject Template') WHERE name='Payment Rejected Template';
INSERT autoresponders (type,name,subject,contents,contents_html,helpid,description) SELECT 3, name, 'an', `value`, value_alternate,50,description FROM setting WHERE name = 'Overdue Invoice Template';
UPDATE autoresponders SET subject = 	( SELECT value FROM setting WHERE name='Overdue Invoice Subject Template') WHERE name='Overdue Invoice Template';
INSERT autoresponders (type,name,subject,contents,contents_html,helpid,description) SELECT 3, name, 'an', `value`, value_alternate,50,description FROM setting WHERE name = 'Batch Invoice Notification Template';
UPDATE autoresponders SET subject = 	( SELECT value FROM setting WHERE name='Batch Invoice Notification Subject Template') WHERE name='Batch Invoice Notification Template';
INSERT autoresponders (type,name,subject,contents,contents_html,helpid,description) SELECT 3, name, 'an', `value`, value_alternate,51,description FROM setting WHERE name = 'Expiring CC Template';
UPDATE autoresponders SET subject = 	( SELECT value FROM setting WHERE name='Expiring CC Subject Template') WHERE name='Expiring CC Template';

# Add all the domain email setting to autoresponder
INSERT autoresponders (type,name,subject,contents,contents_html,helpid,description) SELECT 4, name, 'an', `value`, value_alternate,52,description FROM setting WHERE name = 'Domain Reminder Template';
UPDATE autoresponders SET subject = 	( SELECT value FROM setting WHERE name='Domain Reminder Subject Template') WHERE name='Domain Reminder Template';

# Add all the other email setting to autoresponder
INSERT autoresponders (type,name,subject,contents,contents_html,helpid,description) SELECT 5, name, 'an', `value`, value_alternate,53,description FROM setting WHERE name = 'Forgot Password Template';
UPDATE autoresponders SET subject = 	( SELECT value FROM setting WHERE name='Forgot Password Subject Template') WHERE name='Forgot Password Template';
INSERT autoresponders (type,name,subject,contents,contents_html,helpid,description) SELECT 5, name, 'an', `value`, value_alternate,54,description FROM setting WHERE name = 'Get New Password Template';
UPDATE autoresponders SET subject = ( SELECT value FROM setting WHERE name='Get New Password Subject Template') WHERE name='Get New Password Template';
INSERT autoresponders (type,name,subject,contents,contents_html,helpid,description) SELECT 5, name, 'an', `value`, value_alternate,55,description FROM setting WHERE name = 'Account Rejected Template';
UPDATE autoresponders SET subject = 	( SELECT value FROM setting WHERE name='Account Rejected Subject Template') WHERE name='Account Rejected Template';

# Add all the support email setting to autoresponder
INSERT autoresponders (type,name,subject,contents,contents_html,helpid,description) SELECT 7, name, 'an', `value`, value_alternate,60,description FROM setting WHERE name = 'Support Ticket Template';
UPDATE autoresponders SET subject = ( SELECT value FROM setting WHERE name='Support Ticket Subject Template') WHERE name='Support Ticket Template';
INSERT autoresponders (type,name,subject,contents,contents_html,helpid,description) SELECT 7, name, 'an', `value`, value_alternate,60,description FROM setting WHERE name = 'Support Ticket Assigned Template';
UPDATE autoresponders SET subject = ( SELECT value FROM setting WHERE name='Support Ticket Assigned Subject Template') WHERE name='Support Ticket Assigned Template';
INSERT autoresponders (type,name,subject,contents,contents_html,helpid,description) SELECT 7, name, 'an', `value`, value_alternate,61,description FROM setting WHERE name = 'Feedback Request for Closed Tickets Template';
UPDATE autoresponders SET subject = ( SELECT value FROM setting WHERE name='Feedback Request for Closed Tickets Subject Template') WHERE name='Feedback Request for Closed Tickets Template';
INSERT autoresponders (type,name,subject,contents,contents_html,helpid,description) SELECT 7, name, 'an', `value`, value_alternate,62,description FROM setting WHERE name = 'AutoClose Ticket Service Template';
UPDATE autoresponders SET subject = ( SELECT value FROM setting WHERE name='AutoClose Ticket Service Subject Template') WHERE name='AutoClose Ticket Service Template';
INSERT autoresponders (type,name,subject,contents,contents_html,helpid,description) SELECT 7, name, 'an', `value`, value_alternate,63,description FROM setting WHERE name = 'Notify Support For New High Priority Tickets Template';
UPDATE autoresponders SET subject = ( SELECT value FROM setting WHERE name='Notify Support For New High Priority Tickets Subject Template') WHERE name='Notify Support For New High Priority Tickets Template';
INSERT autoresponders (type,name,subject,contents,contents_html,helpid,description) SELECT 7, name, 'an', `value`, value_alternate,63,description FROM setting WHERE name = 'Notify Department Lead For New Ticket Template';
UPDATE autoresponders SET subject = ( SELECT value FROM setting WHERE name='Notify Department Lead For New Ticket Subject Template') WHERE name='Notify Department Lead For New Ticket Template';
INSERT autoresponders (type,name,subject,contents,contents_html,helpid,description) SELECT 7, name, 'an', `value`, value_alternate,63,description FROM setting WHERE name = 'Notify Department List For New Ticket Template';
UPDATE autoresponders SET subject = ( SELECT value FROM setting WHERE name='Notify Department List For New Ticket Subject Template') WHERE name='Notify Department List For New Ticket Template';
INSERT autoresponders (type,name,subject,contents,contents_html,helpid,description) SELECT 7, name, 'an', `value`, value_alternate,64,description FROM setting WHERE name = 'Notify Customer For New Ticket Template';
UPDATE autoresponders SET subject = ( SELECT value FROM setting WHERE name='Notify Customer For New Ticket Subject Template') WHERE name='Notify Customer For New Ticket Template';
INSERT autoresponders (type,name,subject,contents,contents_html,helpid,description) SELECT 7, name, 'an', `value`, value_alternate,64,description FROM setting WHERE name = 'Notify Anonymous For New Ticket Template';
UPDATE autoresponders SET subject = ( SELECT value FROM setting WHERE name='Notify Anonymous For New Ticket Subject Template') WHERE name='Notify Anonymous For New Ticket Template';
INSERT autoresponders (type,name,subject,contents,contents_html,helpid,description) SELECT 7, name, 'an', `value`, value_alternate,65,description FROM setting WHERE name = 'Notify Assignee For Ticket Reply Template';
UPDATE autoresponders SET subject = ( SELECT value FROM setting WHERE name='Notify Assignee For Ticket Reply Subject Template') WHERE name='Notify Assignee For Ticket Reply Template';
INSERT autoresponders (type,name,subject,contents,contents_html,helpid,description) SELECT 7, name, 'an', `value`, value_alternate,66,description FROM setting WHERE name = 'Notify For New FeedBack Template';
UPDATE autoresponders SET subject = ( SELECT value FROM setting WHERE name='Get New Password Subject Template') WHERE name='Notify For New FeedBack Template';


# -----------------------------------------------------------
# Team Status Autoresponder Email Templates
# -----------------------------------------------------------
INSERT autoresponders (`type`,`name`,subject,contents,contents_html,description,helpid) VALUES( 6,'Team Status Reply Template','Team Status Reply',"[TEAMSTATUS]\r\n\r\nIn reply to [REPLIEDTEAMSTATUSUSERNAME] ([REPLIEDTEAMSTATUSDATE]):\r\n\r\n> [REPLIEDTEAMSTATUS]","<HTML><head></head><body>[TEAMSTATUS]<br />\r\n<br />\r\nIn reply to [REPLIEDTEAMSTATUSUSERNAME] ([REPLIEDTEAMSTATUSDATE]):<br />\r\n<br />\r\n> [REPLIEDTEAMSTATUS]</body></HTML>",'E-mail send to a user when someone replies to one of his Team Status.',56);
INSERT autoresponders (`type`,`name`,subject,contents,contents_html,description,helpid) VALUES( 6,'Team Status Activity Template','Your Team Status activity',"Here are the latest updates:\r\n\r\n\r\n[TEAMSTATUSDYNAMICBLOCK]","<HTML><head></head><body>Here are the latest updates:<br />\r\n<br />\r\n<br />\r\n[TEAMSTATUSDYNAMICBLOCK]</body></HTML>",'E-mail send to the Team Status users, to notify them the activity on Team Status.',57);
INSERT autoresponders (`type`,`name`,subject,contents,contents_html,description,helpid) VALUES( 6,'Team Status Activity Dynamic Block Template','na',"[TEAMSTATUSUSERNAME][TEAMSTATUSREPLYINFO]: [TEAMSTATUS]\r\n[TEAMSTATUSDATE]\r\n\r\n","[TEAMSTATUSUSERNAME][TEAMSTATUSREPLYINFO]: [TEAMSTATUS]<br />\r\n[TEAMSTATUSDATE]<br />\r\n<br />\r\n",'Dynamic block used to show the Team Status.',58);
INSERT autoresponders (`type`,`name`,subject,contents,contents_html,description,helpid) VALUES( 6,'Team Status Activity Reply Template','na'," in reply to [REPLIEDTEAMSTATUSUSERNAME]"," in reply to [REPLIEDTEAMSTATUSUSERNAME]",'Text to add when a Team Status is a  reply of another Team Status.',59);
