CREATE TABLE `canned_response` (
`id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`name` VARCHAR( 25 ) NOT NULL ,
`response` MEDIUMTEXT NOT NULL,
`userid` INT( 11 ) NOT NULL DEFAULT '0'
) DEFAULT CHARACTER SET utf8, ENGINE=MyISAM AUTO_INCREMENT=1 ;