<table cellpadding="5" cellspacing="0">
    <tr>
        <td>
            <label class="fieldlabel"><?php echo $this->user->lang("Select a Billing Type");?></label>
            <select id="billingtypeid" name="billingtypeid" <?php if(!$this->canEdit){ echo "disabled";} ?> >
              <?php foreach ( $this->billingTypes as $type ) { ?>
                <option <?php if ( $this->billingType == $type['id'] ) {?> selected="selected" <?php } ?> value="<?php echo $type['id']; ?>"><?php echo $type['name']; ?></option>
              <?php } ?>
            </select>
        </td>
        <td>
             <label class="fieldlabel"><?php echo $this->user->lang("Due Date");?></label>
             <input class="required datepicker" style="width: 200px" type="text" name="duedate" value="<?php echo $this->duedate; ?>" <?php if(!$this->canEditDate){ echo "disabled";} ?> />
        </td>
    </tr>
    <tr>
        <td colspan="3">
            <label class="fieldlabel"><?php echo $this->user->lang("Charge Name");?></label>
            <input id="name" style="width: 450px" class="required" type="text" name="name" value="<?php echo $this->name; ?>" <?php if(!$this->canEdit){ echo "disabled";} ?> />
        </td>
    </tr>
    <tr>
        <td colspan="3">
            <label class="fieldlabel"><?php echo $this->user->lang("Charge Description");?></label>
            <textarea id="desc" class="required" style="height: 90px" name="desc" <?php if(!$this->canEdit){ echo "disabled";} ?> ><?php echo $this->description; ?></textarea>
        </td>
    </tr>
    <tr>
        <td>
            <label class="fieldlabel"><?php echo $this->user->lang("Applies to package");?></label>
            <select name="appliestoid" <?php if(!$this->canEdit){ echo "disabled";} ?> >
                <option value="0">None</option>
                <?php foreach ( $this->packages as $package ) { ?>
                <option <?php if ( $this->appliesTo == $package['id'] ) { ?> selected="selected" <?php } ?> value="<?php echo $package['id']; ?>"><?php echo $this->escape($package['name']) ?></option>
                <?php } ?>
            </select>
        </td>
        <td>
            <table>
                <tr>
                    <td>
                        <label class="fieldlabel" style="width: 119px"><?php echo $this->user->lang("Price per unit");?></label>
                        <input id="price" type="text" class="price required" style="width: 119px" name="price" value="<?php echo $this->price; ?>" <?php if(!$this->canEditPrice){ echo "disabled";} ?> />
                    </td>
                    <td>
                        <span class='tip-target' data-toggle="tooltip" data-placement='top' title="<?php echo $this->user->lang('Prices will be multiplied by the quantity.'); ?>">
                            <label class="fieldlabel" style="width: 70px"><?php echo $this->user->lang("Quantity");?></label>
                            <input id="quantity" type="number" step="0.01" min="0" class="quantity required" style="width: 70px" name="quantity" value="<?php echo $this->quantity; ?>" <?php if(!$this->canEditQuantity){ echo "disabled";} ?> />
                        </span>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td colspan="3">
            <input type="checkbox" name="taxable" <?php echo $this->taxableChecked; ?> <?php if(!$this->canEdit){ echo "disabled";} ?> /> <?php echo $this->user->lang('Tax this entry?'); ?> <br/>
        </td>
    </tr>
    <tr>
        <td>
            <label class="fieldlabel"><?php echo $this->user->lang("Billing Cycle");?></label>
            <select name="paymentterm" <?php if(!$this->canEdit){ echo "disabled";} ?> >
                <?php foreach ($this->billingcycles as $billingCycleId => $billingCycleData) {?>
                    <option <?php if ( $this->cycle == $billingCycleId ) { ?> selected="selected" <?php } ?> value="<?php echo $billingCycleId; ?>"><?php echo $this->user->lang($billingCycleData['name']); ?></option>
                <?php } ?>
            </select>
        </td>
        <td>
            <span class='tip-target' data-toggle="tooltip" data-placement='top' title="<?php echo $this->user->lang('<b>Duration in months</b> should be used only for Billing Cycles which have their Time Unit in Months or Years.').'<br/>'.$this->user->lang('The value should be an integer number representing how many months it will be recurring.'); ?>">
                <label class="fieldlabel"><?php echo $this->user->lang("Duration in months");?></label>
                <input type="text" name="recurringmonths" <?php if(!$this->canEdit){ echo "disabled";} ?> />
            </span>
        </td>
    </tr>
    <?php if($this->allowNewSubscriptions || $this->subscriptionID){ ?>
    <tr>
         <td>
            <label class="fieldlabel"><?php echo $this->user->lang("Subscription");?></label>
            <select name="paymentSubscription" <?php if(!$this->canEdit){ echo "disabled";} ?> >
                <option <?php if ( $this->subscription == 0 ) {?> selected="selected" <?php } ?> value="0"><?php echo $this->user->lang('No subscription'); ?></option>
                <option <?php if ( $this->subscription == 1 ) {?> selected="selected" <?php } ?> value="1"><?php echo $this->user->lang('Subscription'); ?></option>
            </select>
        </td>
         <td>
            <?php if($this->subscriptionID){ ?>
            <label class="fieldlabel"><?php echo $this->user->lang("Subscription ID");?></label>
            <input type="text" name="subscriptionid" value="<?php echo $this->subscriptionID; ?>" <?php if(!$this->canEdit){ echo "disabled";} ?> />
            <?php } ?>
        </td>
    </tr>
    <?php } ?>
</table>
<input id="id" type="hidden" name="id" value="<?php echo $this->id; ?>" />

<script data-cfasync="false" type="text/javascript">
    $(document).ready(function() {
        <?php if (!$this->canEdit && !$this->canEditDate && !$this->canEditPrice && !$this->canEditQuantity) { ?>
              $('#rich-button-submit').hide();
        <?php } else { ?>
              $('#rich-button-submit').show();
        <?php } ?>
        clientexec.postpageload('.richwindow');
        if ( $('#id').val() == '0' ) {
            populateFields($('#billingtypeid').val());
        }

        $('.price').each(function() {
            $(this).keydown(function (e) {
                // Allow: delete, backspace, tab, escape, enter, - (109, 173, 189), . (110, 190)
                if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 109, 173, 189, 110, 190]) !== -1 ||
                     // Allow: Ctrl+A,Ctrl+C,Ctrl+V, Command+A
                     ((e.keyCode == 65 || e.keyCode == 86 || e.keyCode == 67) && (e.ctrlKey === true || e.metaKey === true)) ||
                     // Allow: end, home, left, up, right, down
                    (e.keyCode >= 35 && e.keyCode <= 40)) {
                         // let it happen, don't do anything
                         return;
                }
                // Ensure that it is a number and stop the keypress
                if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
                    e.preventDefault();
                }
            });
        });

        $('.quantity').each(function() {
            $(this).keydown(function (e) {
                // Allow: delete, backspace, tab, escape, enter, . (110, 190)
                if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 ||
                     // Allow: Ctrl+A
                    (e.keyCode == 65 && e.ctrlKey === true) ||
                     // Allow: end, home, left, up, right, down
                    (e.keyCode >= 35 && e.keyCode <= 40)) {
                         // let it happen, don't do anything
                         return;
                }
                // Ensure that it is a number and stop the keypress
                if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
                    e.preventDefault();
                }
            });
        });
    });

    $('#billingtypeid').change(function() {
        var billingId = $(this).val();
        if ( $('#name').val() != '' ) {
            RichHTML.msgBox(lang('Your data will be overwritten.  Are you sure you want to replace the text fields with the default content of the selected billing type?'),
            {
                type:"confirm"
            }, function(result) {
                if(result.btn === lang("Yes")) {
                    populateFields(billingId);
                }
            });
        } else {
            populateFields(billingId);
        }
    });

    function populateFields(id)
    {
        $.get('index.php?fuse=billing&controller=billingtype&action=gettype&id=' + id, function(data) {
            $('#name').val(data.description);
            $('#desc').val(data.detail);
            $('#price').val(data.price);
        }, 'json');
        $('#quantity').val(1);
    }
</script>
