<style type="text/css">
    .table2 tbody tr:nth-child(odd) td, .table2 tbody tr:nth-child(even) td {
        border-top: 0px;
        background-color: transparent;
    }
    tr.FreeDomainOptionsHeader, td.FreeDomainOptionsHeader {
        margin-bottom: 0px;
        padding-bottom: 0px;
    }
    .table2 tbody tr:nth-child(odd) td.FreeDomainOptionsHeaderBGC, .table2 tbody tr:nth-child(even) td.FreeDomainOptionsHeaderBGC {
        background-color: rgb(228, 228, 228);
    }
    tr.FreeDomainOptionsBody, td.FreeDomainOptionsBody {
        margin-top: 0px;
        padding-top: 0px;
    }
    .table2 tbody tr:nth-child(odd) td.FreeDomainOptionsBodyBGC, .table2 tbody tr:nth-child(even) td.FreeDomainOptionsBodyBGC {
        background-color: rgb(244, 244, 244);
    }
    .tableFreeDomain {
        margin-top: 8px;
        margin-bottom: 8px;
    }
    td.FirstRowWidth {
        width: 150px;
    }
    td.TLDRowWidth, select.TLDRowWidth {
        width: 147px;
    }
    label.FreeDomainOptionsLabel {
        text-align: left;
        font-weight: bold;
        margin-bottom: 10px;
        margin-top: -5px;
        font-size: 16px;
    }
    label.FreeDomainOptionsMargin, div.FreeDomainOptionsMargin {
        margin-left: 10px;
    }
    label.FreeDomainOptionsLabel2 {
        text-align:left;
        font-weight:bold;
    }
</style>

<script data-cfasync="false" type="text/javascript">
    $(document).ready(function() {
        $('.price').each(function() {
            $(this).keydown(function (e) {
                // Allow: delete, backspace, tab, escape, enter, . (110, 190)
                if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 ||
                    // Allow: Ctrl+A
                    (e.keyCode == 65 && e.ctrlKey === true) ||
                    // Allow: Ctrl+C
                    (e.keyCode == 67 && e.ctrlKey === true) ||
                     // Allow: Ctrl+V
                    (e.keyCode == 86 && e.ctrlKey === true) ||
                     // Allow: home, end, left, right
                    (e.keyCode >= 35 && e.keyCode <= 39)) {
                         // let it happen, don't do anything
                         return;
                }
                // Ensure that it is a number and stop the keypress
                if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
                    e.preventDefault();
                }
            });
        });
        clientexec.postpageload('#pricingtab');
    });

    function toggleFreeDomainFields (value, cycle)
    {
        if (value == 0) {
            $('#freedomaindisplay'+cycle).hide();
        } else {
            $('#freedomaindisplay'+cycle).show();
        }
    }

    //Code for prices in different currencies
    function toggleCurrencyFreeDomainFields (currency, value, cycle)
    {
        if (value == 0) {
            $('#'+currency+'_freedomaindisplay'+cycle).hide();
        } else {
            $('#'+currency+'_freedomaindisplay'+cycle).show();
        }
    }

    function productPricingFilterBy (el,filter)
    {
        $(el).closest('.nav-pills').find('li').removeClass('active')
        $(el).closest('li').addClass('active');

        $('.currencyprice').hide();
        $('.currencyCode'+filter).show();
    }
    //Code for prices in different currencies
</script>

<?php
    //Code for prices in different currencies
    include_once 'modules/billing/models/CurrencyGateway.php';

    $gateway = new CurrencyGateway($this->user);
    $currencies = $gateway->GetCurrencies();

    if ($currencies['totalcount'] > 1) {
?>
        <ul class="nav nav-pills">
<?php
        foreach ($currencies['currencies'] as $currencyValues) {
?>
            <li <?php if ($currencyValues['isdefault']) { echo 'class="active"'; } ?> >
                <a <?php if ($currencyValues['isdefault']) { echo 'class="default-language-tab"'; } ?> href="javascript:void(0)" onclick="productPricingFilterBy(this,'<?php echo $currencyValues['abrv']; ?>')"><?php echo $currencyValues['name']; ?></a>
            </li>
<?php
        }
?>
        </ul>
<?php
    }
    //Code for prices in different currencies
?>

<div class="fieldwrapper">
    <form id="pricingtab">
        <table class="table table-striped" width="100%">
            <thead>
            <tr>
                <td>
                    <table class="table2" width="100%">
                        <thead>
                        <tr class="FreeDomainOptionsHeader FreeDomainOptionsBody">
                            <td class="FreeDomainOptionsHeader FreeDomainOptionsBody FirstRowWidth">
                            </td>
                            <td class="FreeDomainOptionsHeader FreeDomainOptionsBody" width="65">
                                <label style="text-align:center;font-weight:bold;" class="fieldlabel"><?php echo $this->user->lang("Price");?></label>
                            </td>
                            <td class="FreeDomainOptionsHeader FreeDomainOptionsBody" width="65">
                                <label style="text-align:center;font-weight:bold;" class="fieldlabel"><?php echo $this->user->lang("Setup");?></label>
                            </td>
                            <td class="FreeDomainOptionsHeader FreeDomainOptionsBody" width="100">
                                <label style="text-align:center;font-weight:bold;" class="fieldlabel"><?php echo $this->user->lang("Allow in signup?");?></label>
                            </td>
                            <td class="FreeDomainOptionsHeader FreeDomainOptionsBody">
                                <?php if ($this->domain_product !== false) { ?>
                                <!-- THIS CELL IS TO DISPLAY THE FREE DOMAIN OPTIONS -->
                                <label class="fieldlabel FreeDomainOptionsLabel2"><?php echo $this->user->lang("Free Domain?");?></label>
                                <!-- /THIS CELL IS TO DISPLAY THE FREE DOMAIN OPTIONS -->
                                <?php } ?>
                            </td>
                        </tr>
                        </thead>
                    </table>
                </td>
            </tr>
            </thead>
            <tbody>

            <?php foreach ($this->priceExtraData as $cycle => $extraDataValues) {
                if ($cycle == 0) {
                    continue;
                } ?>

                <tr>
                    <td>
                        <table class="table2">
                            <tbody>
                            <tr>
                                <td class="FirstRowWidth">
                                    <?php echo $this->user->lang($this->priceExtraData[$cycle]['price_name']);?>
                                </td>
                                <td width="65">
<!-- CODE FOR PRICES IN DIFFERENT CURRENCIES -->
<?php
    if ($currencies['totalcount'] > 1) {
        foreach ($currencies['currencies'] as $currencyValues) {
?>
                                    <span class="currencyprice currencyCode<?php echo $currencyValues['abrv']; ?>" <?php if (!$currencyValues['isdefault']) { echo 'style="display: none"'; } ?> ><input class="price" type="text" value="<?php echo $this->priceExtraDataCurrencies[$currencyValues['abrv']][$cycle]['price'];?>" name="<?php echo $currencyValues['abrv']; ?>_price<?php echo $cycle; ?>" <?php if ($currencyValues['isdefault']) { echo 'id="maincurrencyprice'.$cycle.'"'; } ?> style="width:50px;"/></span>
<?php
        }
    } else {
?>
                                    <input class="price" type="text" value="<?php echo $this->priceExtraData[$cycle]['price'];?>" name="price<?php echo $cycle; ?>" id="maincurrencyprice<?php echo $cycle; ?>" style="width:50px;"/>
<?php
    }
?>
<!-- /CODE FOR PRICES IN DIFFERENT CURRENCIES -->
                                </td>
                                <td width="65">
<!-- CODE FOR PRICES IN DIFFERENT CURRENCIES -->
<?php
    if ($currencies['totalcount'] > 1) {
        foreach ($currencies['currencies'] as $currencyValues) {
?>
                                    <span class="currencyprice currencyCode<?php echo $currencyValues['abrv']; ?>" <?php if (!$currencyValues['isdefault']) { echo 'style="display: none"'; } ?> ><input class="price" type="text" value="<?php echo $this->priceExtraDataCurrencies[$currencyValues['abrv']][$cycle]['setup'];?>" name="<?php echo $currencyValues['abrv']; ?>_setup<?php echo $cycle; ?>" <?php if ($currencyValues['isdefault']) { echo 'id="maincurrencysetup'.$cycle.'"'; } ?> style="width:50px;"/></span>
<?php
        }
    } else {
?>
                                    <input class="price" type="text" value="<?php echo $this->priceExtraData[$cycle]['setup'];?>" name="setup<?php echo $cycle; ?>" id="maincurrencysetup<?php echo $cycle; ?>" style="width:50px;"/>
<?php
    }
?>
<!-- /CODE FOR PRICES IN DIFFERENT CURRENCIES -->
                                </td>
                                <td width="100" style="text-align:center;">
<!-- CODE FOR PRICES IN DIFFERENT CURRENCIES -->
<?php
    if ($currencies['totalcount'] > 1) {
        foreach ($currencies['currencies'] as $currencyValues) {
?>
                                    <span class="currencyprice currencyCode<?php echo $currencyValues['abrv']; ?>" <?php if (!$currencyValues['isdefault']) { echo 'style="display: none"'; } ?> ><input type="checkbox" name="<?php echo $currencyValues['abrv']; ?>_price<?php echo $cycle; ?>_checked" <?php if ($currencyValues['isdefault']) { echo 'id="maincurrencyprice'.$cycle.'_checked"'; } ?> value="1" <?php if ($this->priceExtraDataCurrencies[$currencyValues['abrv']][$cycle]['price_checked'] == 1) echo "checked";?> /></span>
<?php
        }
    } else {
?>
                                    <input type="checkbox" name="price<?php echo $cycle; ?>_checked" id="maincurrencyprice<?php echo $cycle; ?>_checked" value="1" <?php if ($this->priceExtraData[$cycle]['price_checked'] == 1) echo "checked";?> />
<?php
    }
?>
<!-- /CODE FOR PRICES IN DIFFERENT CURRENCIES -->
                                </td>
                                <td>
                                    <?php if ($this->domain_product !== false) { ?>
                                    <!-- THIS CELL IS TO DISPLAY THE FREE DOMAIN OPTIONS -->
                                    <span data-toggle="tooltip" title='<?php echo $this->user->lang("* Select \"One-Time\" for the domain to be free only the first billing period.\n* Select \"Recurring\" for the domain to be free on every billing period.");?>'>
<!-- CODE FOR PRICES IN DIFFERENT CURRENCIES -->
<?php
    if ($currencies['totalcount'] > 1) {
        foreach ($currencies['currencies'] as $currencyValues) {
?>
                                    <span class="currencyprice currencyCode<?php echo $currencyValues['abrv']; ?>" <?php if (!$currencyValues['isdefault']) { echo 'style="display: none"'; } ?> ><select name="<?php echo $currencyValues['abrv']; ?>_freedomain<?php echo $cycle; ?>" <?php if ($currencyValues['isdefault']) { echo 'id="maincurrencyfreedomain'.$cycle.'"'; } ?> style="width: 100px;" onchange="toggleCurrencyFreeDomainFields('<?php echo $currencyValues['abrv']; ?>', this.value, '<?php echo $cycle; ?>')">
                                            <option <?php echo ($this->priceExtraDataCurrencies[$currencyValues['abrv']][$cycle]['freedomain'] == 0)? "selected" : ""; ?> value="0"><?php echo $this->user->lang("None");?></option>
                                            <option <?php echo ($this->priceExtraDataCurrencies[$currencyValues['abrv']][$cycle]['freedomain'] == 1)? "selected" : ""; ?> value="1"><?php echo $this->user->lang("One-Time");?></option>
                                            <option <?php echo ($this->priceExtraDataCurrencies[$currencyValues['abrv']][$cycle]['freedomain'] == 2)? "selected" : ""; ?> value="2"><?php echo $this->user->lang("Recurring");?></option>
                                        </select></span>
<?php
        }
    } else {
?>
                                        <select name="freedomain<?php echo $cycle; ?>" id="maincurrencyfreedomain<?php echo $cycle; ?>" style="width: 100px;" onchange="toggleFreeDomainFields(this.value, '<?php echo $cycle; ?>')">
                                            <option <?php echo ($this->priceExtraData[$cycle]['freedomain'] == 0)? "selected" : ""; ?> value="0"><?php echo $this->user->lang("None");?></option>
                                            <option <?php echo ($this->priceExtraData[$cycle]['freedomain'] == 1)? "selected" : ""; ?> value="1"><?php echo $this->user->lang("One-Time");?></option>
                                            <option <?php echo ($this->priceExtraData[$cycle]['freedomain'] == 2)? "selected" : ""; ?> value="2"><?php echo $this->user->lang("Recurring");?></option>
                                        </select>
<?php
    }
?>
<!-- /CODE FOR PRICES IN DIFFERENT CURRENCIES -->
                                    </span>
                                    <!-- THIS CELL IS TO DISPLAY THE FREE DOMAIN OPTIONS -->
                                    <?php } ?>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                        <?php if ($this->domain_product !== false) { ?>
<!-- CODE FOR PRICES IN DIFFERENT CURRENCIES -->
<?php
    if ($currencies['totalcount'] > 1) {
        foreach ($currencies['currencies'] as $currencyValues) {
?>
                    <span class="currencyprice currencyCode<?php echo $currencyValues['abrv']; ?>" <?php if (!$currencyValues['isdefault']) { echo 'style="display: none"'; } ?> >
                        <!-- THESE CELLS ARE TO DISPLAY THE FREE DOMAIN CONFIGURATION -->
                        <table class="table2 tableFreeDomain" id="<?php echo $currencyValues['abrv']; ?>_freedomaindisplay<?php echo $cycle; ?>" style="display: <?php echo $this->priceExtraDataCurrencies[$currencyValues['abrv']][$cycle]['freedomaindisplay']; ?>">
                            <tbody>
                            <tr class="FreeDomainOptionsHeader">
                                <td class="FreeDomainOptionsHeader FirstRowWidth">
                                </td>
                                <td colspan="2" class="FreeDomainOptionsHeader FreeDomainOptionsHeaderBGC">
                                    <label class="fieldlabel FreeDomainOptionsLabel FreeDomainOptionsMargin"><?php echo $this->user->lang("Free Domain Options");?></label>
                                </td>
                            </tr>
                            <tr class="FreeDomainOptionsBody">
                                <td class="FirstRowWidth FreeDomainOptionsBody">
                                </td>
                                <td class="FreeDomainOptionsBody FreeDomainOptionsBodyBGC TLDRowWidth">
                                    <label class="fieldlabel FreeDomainOptionsMargin FreeDomainOptionsLabel2"><?php echo $this->user->lang("TLD");?></label>
                                    <div class="FreeDomainOptionsMargin">
                                        <select multiple="multiple" placeholder="Select tld(s)" class="TLDRowWidth" name="<?php echo $currencyValues['abrv']; ?>_domain_extension<?php echo $cycle; ?>[]" <?php if ($currencyValues['isdefault']) { echo 'id="maincurrencydomain_extension'.$cycle.'[]"'; } ?>>
                                            <?php foreach($this->packages as $package) {
                                                $selected = (is_array($this->priceExtraDataCurrencies[$currencyValues['abrv']][$cycle]['domain_extension']) && in_array($package['id'], $this->priceExtraDataCurrencies[$currencyValues['abrv']][$cycle]['domain_extension'])) ? "selected" : "";?>
                                                <option <?php echo $selected; ?> value="<?php echo $package['id'];?>"><?php echo $package['planname'];?></option>
                                            <?php } ?>
                                        </select>
                                    </div>
                                </td>
                                <td class="FreeDomainOptionsBody FreeDomainOptionsBodyBGC">
                                    <label class="fieldlabel FreeDomainOptionsLabel2"><?php echo $this->user->lang("Domain Billing Cycle");?></label>
                                    <select multiple="multiple" placeholder="Select billing cycle(s)" style="width: 473px;" name="<?php echo $currencyValues['abrv']; ?>_domain_cycle<?php echo $cycle; ?>[]" <?php if ($currencyValues['isdefault']) { echo 'id="maincurrencydomain_cycle'.$cycle.'[]"'; } ?>>
                                        <?php foreach ($this->periods as $periods) {
                                            $selected = (is_array($this->priceExtraDataCurrencies[$currencyValues['abrv']][$cycle]['domain_cycle']) && in_array($periods['period'], $this->priceExtraDataCurrencies[$currencyValues['abrv']][$cycle]['domain_cycle'])) ? "selected" : "";?>
                                            <option <?php echo $selected; ?> value="<?php echo $periods['period'];?>" > <?php echo $periods['name'];?> </option>
                                        <?php } ?>
                                    </select>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                        <!-- /THESE CELLS ARE TO DISPLAY THE FREE DOMAIN CONFIGURATION -->
                    </span>
<?php
        }
    } else {
?>
                        <!-- THESE CELLS ARE TO DISPLAY THE FREE DOMAIN CONFIGURATION -->
                        <table class="table2 tableFreeDomain" id="freedomaindisplay<?php echo $cycle; ?>" style="display: <?php echo $this->priceExtraData[$cycle]['freedomaindisplay']; ?>">
                            <tbody>
                            <tr class="FreeDomainOptionsHeader">
                                <td class="FreeDomainOptionsHeader FirstRowWidth">
                                </td>
                                <td colspan="2" class="FreeDomainOptionsHeader FreeDomainOptionsHeaderBGC">
                                    <label class="fieldlabel FreeDomainOptionsLabel FreeDomainOptionsMargin"><?php echo $this->user->lang("Free Domain Options");?></label>
                                </td>
                            </tr>
                            <tr class="FreeDomainOptionsBody">
                                <td class="FirstRowWidth FreeDomainOptionsBody">
                                </td>
                                <td class="FreeDomainOptionsBody FreeDomainOptionsBodyBGC TLDRowWidth">
                                    <label class="fieldlabel FreeDomainOptionsMargin FreeDomainOptionsLabel2"><?php echo $this->user->lang("TLD");?></label>
                                    <div class="FreeDomainOptionsMargin">
                                        <select multiple="multiple" placeholder="Select tld(s)" class="TLDRowWidth" name="domain_extension<?php echo $cycle; ?>[]" id="maincurrencydomain_extension<?php echo $cycle; ?>[]">
                                            <?php foreach($this->packages as $package) {
                                                $selected = (is_array($this->priceExtraData[$cycle]['domain_extension']) && in_array($package['id'], $this->priceExtraData[$cycle]['domain_extension'])) ? "selected" : "";?>
                                                <option <?php echo $selected; ?> value="<?php echo $package['id'];?>"><?php echo $package['planname'];?></option>
                                            <?php } ?>
                                        </select>
                                    </div>
                                </td>
                                <td class="FreeDomainOptionsBody FreeDomainOptionsBodyBGC">
                                    <label class="fieldlabel FreeDomainOptionsLabel2"><?php echo $this->user->lang("Domain Billing Cycle");?></label>
                                    <select multiple="multiple" placeholder="Select billing cycle(s)" style="width: 473px;" name="domain_cycle<?php echo $cycle; ?>[]" id="maincurrencydomain_cycle<?php echo $cycle; ?>[]">
                                        <?php foreach ($this->periods as $periods) {
                                            $selected = (is_array($this->priceExtraData[$cycle]['domain_cycle']) && in_array($periods['period'], $this->priceExtraData[$cycle]['domain_cycle'])) ? "selected" : "";?>
                                            <option <?php echo $selected; ?> value="<?php echo $periods['period'];?>" > <?php echo $periods['name'];?> </option>
                                        <?php } ?>
                                    </select>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                        <!-- /THESE CELLS ARE TO DISPLAY THE FREE DOMAIN CONFIGURATION -->
<?php
    }
?>
<!-- /CODE FOR PRICES IN DIFFERENT CURRENCIES -->
                        <?php } ?>
                    </td>
                </tr>
            <?php } ?>

            <tr>
                <td>
                    <table class="table2">
                        <tbody>
                        <tr>
                            <td class="FirstRowWidth">
                                <?php echo $this->user->lang($this->priceExtraData[0]['price_name']);?>
                            </td>
                            <td width="146">
<!-- CODE FOR PRICES IN DIFFERENT CURRENCIES -->
<?php
    if ($currencies['totalcount'] > 1) {
        foreach ($currencies['currencies'] as $currencyValues) {
?>
                                    <span class="currencyprice currencyCode<?php echo $currencyValues['abrv']; ?>" <?php if (!$currencyValues['isdefault']) { echo 'style="display: none"'; } ?> ><input class="price" type="text" value="<?php echo $this->priceExtraDataCurrencies[$currencyValues['abrv']][0]['price'];?>" name="<?php echo $currencyValues['abrv']; ?>_price0" <?php if ($currencyValues['isdefault']) { echo 'id="maincurrencyprice0"'; } ?> style="width:50px;"/></span>
<?php
        }
    } else {
?>
                                <input class="price" type="text" value="<?php echo $this->priceExtraData[0]['price'];?>" name="price0" id="maincurrencyprice0" style="width:50px;"/>
<?php
    }
?>
<!-- /CODE FOR PRICES IN DIFFERENT CURRENCIES -->
                            </td>
                            <td width="100" style="text-align:center;">
<!-- CODE FOR PRICES IN DIFFERENT CURRENCIES -->
<?php
    if ($currencies['totalcount'] > 1) {
        foreach ($currencies['currencies'] as $currencyValues) {
?>
                                    <span class="currencyprice currencyCode<?php echo $currencyValues['abrv']; ?>" <?php if (!$currencyValues['isdefault']) { echo 'style="display: none"'; } ?> ><input type="checkbox" name="<?php echo $currencyValues['abrv']; ?>_price0_checked" <?php if ($currencyValues['isdefault']) { echo 'id="maincurrencyprice0_checked"'; } ?> value="1" <?php if ($this->priceExtraDataCurrencies[$currencyValues['abrv']][0]['price_checked'] == 1) echo "checked";?> /></span>
<?php
        }
    } else {
?>
                                <input type="checkbox" name="price0_checked" id="maincurrencyprice0_checked" value="1" <?php if ($this->priceExtraData[0]['price_checked'] == 1) echo "checked";?> />
<?php
    }
?>
<!-- /CODE FOR PRICES IN DIFFERENT CURRENCIES -->
                            </td>
                            <td>
                                <?php if ($this->domain_product !== false) { ?>
                                <!-- THIS CELL IS TO DISPLAY THE FREE DOMAIN OPTIONS -->
                                <span data-toggle="tooltip" title='<?php echo $this->user->lang("* Select \"One-Time\" for the domain to be free only the first billing period.\n* Select \"Recurring\" for the domain to be free on every billing period.");?>'>
<!-- CODE FOR PRICES IN DIFFERENT CURRENCIES -->
<?php
    if ($currencies['totalcount'] > 1) {
        foreach ($currencies['currencies'] as $currencyValues) {
?>
                                    <span class="currencyprice currencyCode<?php echo $currencyValues['abrv']; ?>" <?php if (!$currencyValues['isdefault']) { echo 'style="display: none"'; } ?> ><select name="<?php echo $currencyValues['abrv']; ?>_freedomain0" <?php if ($currencyValues['isdefault']) { echo 'id="maincurrencyfreedomain0"'; } ?> style="width: 100px;" onchange="toggleCurrencyFreeDomainFields('<?php echo $currencyValues['abrv']; ?>', this.value, '0')">
                                        <option <?php echo ($this->priceExtraDataCurrencies[$currencyValues['abrv']][0]['freedomain'] == 0)? "selected" : ""; ?> value="0"><?php echo $this->user->lang("None");?></option>
                                        <option <?php echo ($this->priceExtraDataCurrencies[$currencyValues['abrv']][0]['freedomain'] == 1)? "selected" : ""; ?> value="1"><?php echo $this->user->lang("One-Time");?></option>
                                        <option <?php echo ($this->priceExtraDataCurrencies[$currencyValues['abrv']][0]['freedomain'] == 2)? "selected" : ""; ?> value="2"><?php echo $this->user->lang("Recurring");?></option>
                                    </select></span>
<?php
        }
    } else {
?>
                                    <select name="freedomain0" id="maincurrencyfreedomain0" style="width: 100px;" onchange="toggleFreeDomainFields(this.value, '0')">
                                        <option <?php echo ($this->priceExtraData[0]['freedomain'] == 0)? "selected" : ""; ?> value="0"><?php echo $this->user->lang("None");?></option>
                                        <option <?php echo ($this->priceExtraData[0]['freedomain'] == 1)? "selected" : ""; ?> value="1"><?php echo $this->user->lang("One-Time");?></option>
                                        <option <?php echo ($this->priceExtraData[0]['freedomain'] == 2)? "selected" : ""; ?> value="2"><?php echo $this->user->lang("Recurring");?></option>
                                    </select>
<?php
    }
?>
<!-- /CODE FOR PRICES IN DIFFERENT CURRENCIES -->
                                </span>
                                <!-- THIS CELL IS TO DISPLAY THE FREE DOMAIN OPTIONS -->
                                <?php } ?>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                    <?php if ($this->domain_product !== false) { ?>
<!-- CODE FOR PRICES IN DIFFERENT CURRENCIES -->
<?php
    if ($currencies['totalcount'] > 1) {
        foreach ($currencies['currencies'] as $currencyValues) {
?>
                <span class="currencyprice currencyCode<?php echo $currencyValues['abrv']; ?>" <?php if (!$currencyValues['isdefault']) { echo 'style="display: none"'; } ?> >
                    <!-- THESE CELLS ARE TO DISPLAY THE FREE DOMAIN CONFIGURATION -->
                    <table class="table2 tableFreeDomain" id="<?php echo $currencyValues['abrv']; ?>_freedomaindisplay0" style="display: <?php echo $this->priceExtraDataCurrencies[$currencyValues['abrv']][0]['freedomaindisplay']; ?>">
                        <tbody>
                        <tr class="FreeDomainOptionsHeader">
                            <td class="FreeDomainOptionsHeader FirstRowWidth">
                            </td>
                            <td colspan="2" class="FreeDomainOptionsHeader FreeDomainOptionsHeaderBGC">
                                <label class="fieldlabel FreeDomainOptionsLabel FreeDomainOptionsMargin"><?php echo $this->user->lang("Free Domain Options");?></label>
                            </td>
                        </tr>
                        <tr class="FreeDomainOptionsBody">
                            <td class="FirstRowWidth FreeDomainOptionsBody">
                            </td>
                            <td class="FreeDomainOptionsBody FreeDomainOptionsBodyBGC TLDRowWidth">
                                <label class="fieldlabel FreeDomainOptionsMargin FreeDomainOptionsLabel2"><?php echo $this->user->lang("TLD");?></label>
                                <div class="FreeDomainOptionsMargin">
                                    <select multiple="multiple" placeholder="Select tld(s)" class="TLDRowWidth" name="<?php echo $currencyValues['abrv']; ?>_domain_extension0[]" <?php if ($currencyValues['isdefault']) { echo 'id="maincurrencydomain_extension0[]"'; } ?>>
                                        <?php foreach($this->packages as $package) {
                                            $selected = (is_array($this->priceExtraDataCurrencies[$currencyValues['abrv']][0]['domain_extension']) && in_array($package['id'], $this->priceExtraDataCurrencies[$currencyValues['abrv']][0]['domain_extension'])) ? "selected" : "";?>
                                            <option <?php echo $selected; ?> value="<?php echo $package['id'];?>"><?php echo $package['planname'];?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                            </td>
                            <td class="FreeDomainOptionsBody FreeDomainOptionsBodyBGC">
                                <label class="fieldlabel FreeDomainOptionsLabel2"><?php echo $this->user->lang("Domain Billing Cycle");?></label>
                                <select multiple="multiple" placeholder="Select billing cycle(s)" style="width: 473px;" name="<?php echo $currencyValues['abrv']; ?>_domain_cycle0[]" <?php if ($currencyValues['isdefault']) { echo 'id="maincurrencydomain_cycle0[]"'; } ?>>
                                    <?php foreach ($this->periods as $periods) {
                                        $selected = (is_array($this->priceExtraDataCurrencies[$currencyValues['abrv']][0]['domain_cycle']) && in_array($periods['period'], $this->priceExtraDataCurrencies[$currencyValues['abrv']][0]['domain_cycle'])) ? "selected" : "";?>
                                        <option <?php echo $selected; ?> value="<?php echo $periods['period'];?>" > <?php echo $periods['name'];?> </option>
                                    <?php } ?>
                                </select>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                    <!-- /THESE CELLS ARE TO DISPLAY THE FREE DOMAIN CONFIGURATION -->
                </span>
<?php
        }
    } else {
?>
                    <!-- THESE CELLS ARE TO DISPLAY THE FREE DOMAIN CONFIGURATION -->
                    <table class="table2 tableFreeDomain" id="freedomaindisplay0" style="display: <?php echo $this->priceExtraData[0]['freedomaindisplay']; ?>">
                        <tbody>
                        <tr class="FreeDomainOptionsHeader">
                            <td class="FreeDomainOptionsHeader FirstRowWidth">
                            </td>
                            <td colspan="2" class="FreeDomainOptionsHeader FreeDomainOptionsHeaderBGC">
                                <label class="fieldlabel FreeDomainOptionsLabel FreeDomainOptionsMargin"><?php echo $this->user->lang("Free Domain Options");?></label>
                            </td>
                        </tr>
                        <tr class="FreeDomainOptionsBody">
                            <td class="FirstRowWidth FreeDomainOptionsBody">
                            </td>
                            <td class="FreeDomainOptionsBody FreeDomainOptionsBodyBGC TLDRowWidth">
                                <label class="fieldlabel FreeDomainOptionsMargin FreeDomainOptionsLabel2"><?php echo $this->user->lang("TLD");?></label>
                                <div class="FreeDomainOptionsMargin">
                                    <select multiple="multiple" placeholder="Select tld(s)" class="TLDRowWidth" name="domain_extension0[]" id="maincurrencydomain_extension0[]">
                                        <?php foreach($this->packages as $package) {
                                            $selected = (is_array($this->priceExtraData[0]['domain_extension']) && in_array($package['id'], $this->priceExtraData[0]['domain_extension'])) ? "selected" : "";?>
                                            <option <?php echo $selected; ?> value="<?php echo $package['id'];?>"><?php echo $package['planname'];?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                            </td>
                            <td class="FreeDomainOptionsBody FreeDomainOptionsBodyBGC">
                                <label class="fieldlabel FreeDomainOptionsLabel2"><?php echo $this->user->lang("Domain Billing Cycle");?></label>
                                <select multiple="multiple" placeholder="Select billing cycle(s)" style="width: 473px;" name="domain_cycle0[]" id="maincurrencydomain_cycle0[]">
                                    <?php foreach ($this->periods as $periods) {
                                        $selected = (is_array($this->priceExtraData[0]['domain_cycle']) && in_array($periods['period'], $this->priceExtraData[0]['domain_cycle'])) ? "selected" : "";?>
                                        <option <?php echo $selected; ?> value="<?php echo $periods['period'];?>" > <?php echo $periods['name'];?> </option>
                                    <?php } ?>
                                </select>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                    <!-- /THESE CELLS ARE TO DISPLAY THE FREE DOMAIN CONFIGURATION -->
<?php
    }
?>
<!-- /CODE FOR PRICES IN DIFFERENT CURRENCIES -->
                    <?php } ?>
                </td>
            </tr>

            <tr>
                <td>
                    <table class="table2">
                        <tbody>
                        <tr>
                            <td class="FirstRowWidth">
                                <?php echo $this->user->lang("Late Fee");?>
                            </td>
                            <td>
<!-- CODE FOR PRICES IN DIFFERENT CURRENCIES -->
<?php
    if ($currencies['totalcount'] > 1) {
        foreach ($currencies['currencies'] as $currencyValues) {
?>
                                    <span class="currencyprice currencyCode<?php echo $currencyValues['abrv']; ?>" <?php if (!$currencyValues['isdefault']) { echo 'style="display: none"'; } ?> ><input class="price" type="text" value="<?php echo $this->priceMoreDataCurrencies[$currencyValues['abrv']]['latefee'];?>" name="<?php echo $currencyValues['abrv']; ?>_latefee" <?php if ($currencyValues['isdefault']) { echo 'id="maincurrencylatefee"'; } ?> style="width:50px;"/></span>
<?php
        }
    } else {
?>
                                <input class="price" type="text" value="<?php echo $this->latefee;?>" name="latefee" id="maincurrencylatefee" style="width:50px;"/>
<?php
    }
?>
<!-- /CODE FOR PRICES IN DIFFERENT CURRENCIES -->
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
            <tr>
                <td>
                    <table class="table2">
                        <tbody>
                        <tr>
                            <td>
<!-- CODE FOR PRICES IN DIFFERENT CURRENCIES -->
<?php
    if ($currencies['totalcount'] > 1) {
        foreach ($currencies['currencies'] as $currencyValues) {
?>
                                    <span class="currencyprice currencyCode<?php echo $currencyValues['abrv']; ?>" <?php if (!$currencyValues['isdefault']) { echo 'style="display: none"'; } ?> ><label class="checkbox inline"><input type="checkbox" name="<?php echo $currencyValues['abrv']; ?>_taxable" <?php if ($currencyValues['isdefault']) { echo 'id="maincurrencytaxable"'; } ?> value="1" <?php if ($this->priceMoreDataCurrencies[$currencyValues['abrv']]['taxable'] == 1) echo "checked";?> /><?php echo $this->user->lang("Product is Taxable?");?></label></span>
<?php
        }
    } else {
?>
                                <label class="checkbox inline"><input type="checkbox" name="taxable" id="maincurrencytaxable" value="1" <?php if ($this->taxable == 1) echo "checked";?> /><?php echo $this->user->lang("Product is Taxable?");?></label>
<?php
    }
?>
<!-- /CODE FOR PRICES IN DIFFERENT CURRENCIES -->
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
            <tr>
                <td>
                    <table class="table2">
                        <tbody>
                        <tr>
                            <td class="FirstRowWidth">
                                <label class="fieldlabel"><span class='tip-target' data-toggle="tooltip"  data-placement="top" title='Select the day you want to prorate all new orders to.'><?php echo $this->user->lang("Prorate To Day");?></span></label>
                            </td>
                            <td>
                                <span class='tip-target' data-toggle="tooltip" data-placement='top' title="<?php echo $this->user->lang('<b>Prorate To Day</b> and <b>Include Following Payment</b> should be used only for Billing Cycles which have their Time Unit in Months or Years.'); ?>">
<!-- CODE FOR PRICES IN DIFFERENT CURRENCIES -->
<?php
    if ($currencies['totalcount'] > 1) {
        foreach ($currencies['currencies'] as $currencyValues) {
?>
                                    <span class="currencyprice currencyCode<?php echo $currencyValues['abrv']; ?>" <?php if (!$currencyValues['isdefault']) { echo 'style="display: none"'; } ?> ><select name="<?php echo $currencyValues['abrv']; ?>_prorateToDay" <?php if ($currencyValues['isdefault']) { echo 'id="maincurrencyprorateToDay"'; } ?> style="width: 214px;">
                                        <option <?php echo ($this->priceMoreDataCurrencies[$currencyValues['abrv']]['prorateToDay'] == 0)? "selected" : ""; ?> value="0"><?php echo $this->user->lang("Do Not Pro-Rate");?></option>
                                        <?php for ($prorateDay = 1; $prorateDay <= 28; $prorateDay++) { ?>
                                            <option <?php echo ($this->priceMoreDataCurrencies[$currencyValues['abrv']]['prorateToDay'] == $prorateDay)? "selected" : ""; ?> value="<?php echo $prorateDay; ?>"><?php echo $prorateDay; ?></option>
                                        <?php } ?>
                                    </select></span>
<?php
        }
    } else {
?>
                                    <select name="prorateToDay" id="maincurrencyprorateToDay" style="width: 214px;">
                                        <option <?php echo ($this->prorateToDay == 0)? "selected" : ""; ?> value="0"><?php echo $this->user->lang("Do Not Pro-Rate");?></option>
                                        <?php for ($prorateDay = 1; $prorateDay <= 28; $prorateDay++) { ?>
                                            <option <?php echo ($this->prorateToDay == $prorateDay)? "selected" : ""; ?> value="<?php echo $prorateDay; ?>"><?php echo $prorateDay; ?></option>
                                        <?php } ?>
                                    </select>
<?php
    }
?>
<!-- /CODE FOR PRICES IN DIFFERENT CURRENCIES -->
                                </span>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
            <tr>
                <td>
                    <table class="table2">
                        <tbody>
                        <tr>
                            <td class="FirstRowWidth">
                                <label class="fieldlabel"><span class='tip-target' data-toggle="tooltip"  data-placement="top" title='Select if you want to include the next payment when prorating.'><?php echo $this->user->lang("Include Following Payment");?></span></label>
                            </td>
                            <td>
                                <?php if ($this->includeFollowingPayment === null) { $this->includeFollowingPayment = -1; } ?>
                                <span class='tip-target' data-toggle="tooltip" data-placement='top' title="<?php echo $this->user->lang('<b>Prorate To Day</b> and <b>Include Following Payment</b> should be used only for Billing Cycles which have their Time Unit in Months or Years.'); ?>">
<!-- CODE FOR PRICES IN DIFFERENT CURRENCIES -->
<?php
    if ($currencies['totalcount'] > 1) {
        foreach ($currencies['currencies'] as $currencyValues) {
?>
                                    <span class="currencyprice currencyCode<?php echo $currencyValues['abrv']; ?>" <?php if (!$currencyValues['isdefault']) { echo 'style="display: none"'; } ?> ><select name="<?php echo $currencyValues['abrv']; ?>_includeFollowingPayment" <?php if ($currencyValues['isdefault']) { echo 'id="maincurrencyincludeFollowingPayment"'; } ?> style="width: 214px;" >
                                        <option <?php echo ($this->priceMoreDataCurrencies[$currencyValues['abrv']]['includeFollowingPayment'] == -1)? "selected" : ""; ?> value="-1"><?php echo $this->user->lang("Never");?></option>
                                        <option <?php echo ($this->priceMoreDataCurrencies[$currencyValues['abrv']]['includeFollowingPayment'] == 0)? "selected" : ""; ?> value="0" ><?php echo $this->user->lang("If prorating 10 days or less");?></option>
                                        <option <?php echo ($this->priceMoreDataCurrencies[$currencyValues['abrv']]['includeFollowingPayment'] == 2)? "selected" : ""; ?> value="2" ><?php echo $this->user->lang("Always except for monthly payments");?></option>

                                        <!--
                                            This option was added to allow using paypal subscriptions on other than monthly payments.
                                            Without it, for quarterly, semianual and annual payments, if there's prorating and inclusion of the following payment, paypal's subscription
                                            initial trial period would exceed 90 days, so a subscription can't be established.
                                        -->
                                        <option <?php echo ($this->priceMoreDataCurrencies[$currencyValues['abrv']]['includeFollowingPayment'] == 3)? "selected" : ""; ?> value="3" ><?php echo $this->user->lang("Only for monthly payments");?></option>

                                        <option <?php echo ($this->priceMoreDataCurrencies[$currencyValues['abrv']]['includeFollowingPayment'] == 1)? "selected" : ""; ?> value="1" ><?php echo $this->user->lang("Always");?></option>
                                    </select></span>
<?php
        }
    } else {
?>
                                    <select name="includeFollowingPayment" id="maincurrencyincludeFollowingPayment" style="width: 214px;" >
                                        <option <?php echo ($this->includeFollowingPayment == -1)? "selected" : ""; ?> value="-1"><?php echo $this->user->lang("Never");?></option>
                                        <option <?php echo ($this->includeFollowingPayment == 0)? "selected" : ""; ?> value="0" ><?php echo $this->user->lang("If prorating 10 days or less");?></option>
                                        <option <?php echo ($this->includeFollowingPayment == 2)? "selected" : ""; ?> value="2" ><?php echo $this->user->lang("Always except for monthly payments");?></option>

                                        <!--
                                            This option was added to allow using paypal subscriptions on other than monthly payments.
                                            Without it, for quarterly, semianual and annual payments, if there's prorating and inclusion of the following payment, paypal's subscription
                                            initial trial period would exceed 90 days, so a subscription can't be established.
                                        -->
                                        <option <?php echo ($this->includeFollowingPayment == 3)? "selected" : ""; ?> value="3" ><?php echo $this->user->lang("Only for monthly payments");?></option>

                                        <option <?php echo ($this->includeFollowingPayment == 1)? "selected" : ""; ?> value="1" ><?php echo $this->user->lang("Always");?></option>
                                    </select>
<?php
    }
?>
<!-- /CODE FOR PRICES IN DIFFERENT CURRENCIES -->
                                </span>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
            <tr>
                <td>
                    <table class="table2">
                        <tbody>
                        <tr>
                            <td class="FirstRowWidth">
                                <label class="fieldlabel"><span class='tip-target' data-toggle="tooltip"  data-placement="top" title='Enter an existing Coupon Code to have the coupon automatically applied during checkout.'><?php echo $this->user->lang("Automatic Coupon");?></span></label>
                            </td>
                            <td>
<!-- CODE FOR PRICES IN DIFFERENT CURRENCIES -->
<?php
    if ($currencies['totalcount'] > 1) {
        foreach ($currencies['currencies'] as $currencyValues) {
?>
                                    <span class="currencyprice currencyCode<?php echo $currencyValues['abrv']; ?>" <?php if (!$currencyValues['isdefault']) { echo 'style="display: none"'; } ?> ><input type="text" name="<?php echo $currencyValues['abrv']; ?>_automaticCoupon" <?php if ($currencyValues['isdefault']) { echo 'id="maincurrencyautomaticCoupon"'; } ?> value="<?php echo $this->priceMoreDataCurrencies[$currencyValues['abrv']]['automaticCoupon'];?>" style="width:200px;"/></span>
<?php
        }
    } else {
?>
                                <input type="text" name="automaticCoupon" id="maincurrencyautomaticCoupon" value="<?php echo $this->automaticCoupon;?>" style="width:200px;"/>
<?php
    }
?>
<!-- /CODE FOR PRICES IN DIFFERENT CURRENCIES -->
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
            </tbody>
            <tfoot>
            <tr>
                <td>
                    <div class="alert alert-block">
                        <ul>
                            <li><?php echo $this->user->lang("<b>Make sure to configure pricing per currency enabled. Disable any currency that will not be used.</b>");?></li>
                            <li><?php echo $this->user->lang("Addon prices for billing cycles not used in this product will not be available to the client, unless you select the force show option in the addon setup screen.");?></li>
                            <li><?php echo $this->user->lang("<b>Prorate To Day</b> and <b>Include Following Payment</b> will also apply to the addons purchased with the product.");?></li>
                            <li><?php echo $this->user->lang("<b>Prorate To Day</b> and <b>Include Following Payment</b> should be used only for Billing Cycles which have their Time Unit in Months or Years.");?></li>
                        </ul>
                    </div>
                    <div class="form-actions">
                        <div class="pull-right">
                          <button type="submit" class="submit-pricing btn btn-primary"><?php echo $this->user->lang("Save Changes");?></button>
                        </div>
                    </div>
                </td>
            </tr>
            </tfoot>
        </table>
    </form>
</div>