ALTER TABLE `customField` ADD `company_id` INT(11) NOT NULL DEFAULT '0' AFTER `id`;
ALTER TABLE `customField` ADD `isEncrypted` tinyint(1) NOT NULL DEFAULT '0';
ALTER TABLE `customField` CHANGE `desc` `desc` VARCHAR( 250 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `customuserfields` CHANGE `desc` `desc` VARCHAR( 250 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';

INSERT INTO `customField` (`id` ,`groupId` ,`subGroupId` ,`fieldType` ,`name` ,`isRequired` ,`isChangeable` ,`isAdminOnly` ,`fieldOrder` ,`showCustomer` ,`showAdmin` ,`dropDownOptions` ,`inSettings` ,`InSignup`) VALUES (NULL , '2', '2', '0', 'Certificate Id', '0', '0', '0', '0', '0', '0', '', '0', '0');
INSERT INTO `customField` (`id` ,`groupId` ,`subGroupId` ,`fieldType` ,`name` ,`isRequired` ,`isChangeable` ,`isAdminOnly` ,`fieldOrder` ,`showCustomer` ,`showAdmin` ,`dropDownOptions` ,`inSettings` ,`InSignup`) VALUES (NULL , '2', '2', '0', 'Certificate Type', '0', '0', '0', '0', '0', '0', '', '0', '0');
INSERT INTO `customField` (`id` ,`groupId` ,`subGroupId` ,`fieldType` ,`name` ,`isRequired` ,`isChangeable` ,`isAdminOnly` ,`fieldOrder` ,`showCustomer` ,`showAdmin` ,`dropDownOptions` ,`inSettings` ,`InSignup`) VALUES (NULL , '2', '2', '0', 'Certificate Status', '0', '0', '0', '0', '0', '0', '', '0', '0');
INSERT INTO `customField` (`id` ,`groupId` ,`subGroupId` ,`fieldType` ,`name` ,`isRequired` ,`isChangeable` ,`isAdminOnly` ,`fieldOrder` ,`showCustomer` ,`showAdmin` ,`dropDownOptions` ,`inSettings` ,`InSignup`) VALUES (NULL , '2', '2', '0', 'Certificate Expiration Date', '0', '0', '0', '0', '0', '0', '', '0', '0');
INSERT INTO `customField` (`id` ,`groupId` ,`subGroupId` ,`fieldType` ,`name` ,`isRequired` ,`isChangeable` ,`isAdminOnly` ,`fieldOrder` ,`showCustomer` ,`showAdmin` ,`dropDownOptions` ,`inSettings` ,`InSignup`) VALUES (NULL , '2', '2', '0', 'Certificate Domain', '0', '0', '0', '0', '0', '0', '', '0', '0');
INSERT INTO `customField` (`id` ,`groupId` ,`subGroupId` ,`fieldType` ,`name` ,`isRequired` ,`isChangeable` ,`isAdminOnly` ,`fieldOrder` ,`showCustomer` ,`showAdmin` ,`dropDownOptions` ,`inSettings` ,`InSignup`) VALUES (NULL , '2', '2', '10', 'Certificate CSR', '0', '0', '0', '0', '1', '0', '', '1', '1');
INSERT INTO `customField` (`id` ,`groupId` ,`subGroupId` ,`fieldType` ,`name` ,`isRequired` ,`isChangeable` ,`isAdminOnly` ,`fieldOrder` ,`showCustomer` ,`showAdmin` ,`dropDownOptions` ,`inSettings` ,`InSignup`) VALUES (NULL , '2', '2', '0', 'Certificate Admin Email', '0', '0', '0', '0', '1', '0', '', '1', '1');
INSERT INTO `customField` (`id` ,`groupId` ,`subGroupId` ,`fieldType` ,`name` ,`isRequired` ,`isChangeable` ,`isAdminOnly` ,`fieldOrder` ,`showCustomer` ,`showAdmin` ,`dropDownOptions` ,`inSettings` ,`InSignup`) VALUES (NULL , '2', '2', '0', 'Registrar', '0', '0', '0', '0', '0', '0', '', '0', '0');
INSERT INTO `customField` (`id` ,`groupId` ,`subGroupId` ,`fieldType` ,`name` ,`isRequired` ,`isChangeable` ,`isAdminOnly` ,`fieldOrder` ,`showCustomer` ,`showAdmin` ,`dropDownOptions` ,`inSettings` ,`InSignup`) VALUES (NULL , '2', '2', '0', 'Certificate Server Type', '0', '0', '0', '0', '0', '0', '', '0', '0');
