# ---------------------------------------------------------
# ALLOW SETTING OF THE DEFAULT TLD TO SHOW IN THE SIGNUP FORM
# ---------------------------------------------------------
INSERT INTO `setting` VALUES (NULL, 'Default TLD', 'com', NULL , 'Select the TLD that should be preselected in the sign up form.', -1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1);

# ---------------------------------------------------------
# TAX SETTING FOR SETTING RULE TO USE VAT CALCULATIONS
# ---------------------------------------------------------
ALTER TABLE `taxrule` ADD `vat` TINYINT( 4 ) NOT NULL DEFAULT '0';

# ---------------------------------------------------------
# COMPANYADDRESS E-MAIL TEMPLATE TAG
# ---------------------------------------------------------
UPDATE `help` SET `detail` = '[<font class=bodyhighlight>COMPANYNAME</font>] <br> Company name<br>[<font class=bodyhighlight>COMPANYADDRESS</font>] <br> Company address<br>[<font class=bodyhighlight>ACCOUNTINFORMATION</font>]<br> Includes Domain Name, Username, Password, IP<br>[<font class=bodyhighlight>DOMAINNAME</font>]<br> domain name without http://www.<br>[<font class=bodyhighlight>DOMAINUSERNAME</font>]<br> Domain User Name<br>[<font class=bodyhighlight>DOMAINPASSWORD</font>]<br> Domain Password<br>[<font class=bodyhighlight>DOMAINIP</font>]<br> IP Address to Domain<br>[<font class=bodyhighlight>COMPANYURL</font>]<br> URL to your web site<br>[<font class=bodyhighlight>SUPPORTEMAIL</font>]<br> E-mail to support staff<br>[<font class=bodyhighlight>CLIENTAPPLICATIONURL</font>]<br> URL to ClientExec.<br>[<font class=bodyhighlight>FORGOTPASSWORDURL</font>] URL to retrieve forgotten password.<br>[<font class=bodyhighlight>CLIENTNAME</font>]<br>Both first and last name<br>[<font class=bodyhighlight>CLIENTEMAIL</font>]<br>[<font class=bodyhighlight>ORGANIZATION</font>] <br> Client\'s Organization<br>[<font class=bodyhighlight>PLANNAME</font>] <br> Client\'s Plan<br>[<font class=bodyhighlight>NAMESERVERS</font>]<br>lists only hostnames<br>[<font class=bodyhighlight>NAMESERVERSANDIPS</font>]<br>lists both IPs and hostnames<br>[<font class=bodyhighlight>SERVERHOSTNAME</font>]<br>example server1.yourdomain.com<br>[<font class=bodyhighlight>SERVERSHAREDIP</font>]<br>shared IP for server<br>[<font class=bodyhighlight>CUSTOMPROFILE_xxxx</font>]<br>where xxx is custom profile field name<br>[<font class=bodyhighlight>CUSTOMPACKAGE_xxxx</font>]<br>where xxx is custom package field name' WHERE `title`='Welcome Email Tags';
UPDATE `help` SET `detail` = '[<font class=bodyhighlight>CLIENTNAME</font>] <br>[<font class=bodyhighlight>TICKETNUMBER</font>]<br>[<font class=bodyhighlight>DESCRIPTION</font>]<br>[<font class=bodyhighlight>CLIENTAPPLICATIONURL</font>] URL to ClientExec.<BR>[<font class=bodyhighlight>COMPANYNAME</font>] <br>[<font class=bodyhighlight>COMPANYADDRESS</font>] <br>[<font class=bodyhighlight>CUSTOM_xxxx</font>]<br>where xxx is custom field name' WHERE `title`='Ticket Template Tags';
UPDATE `help` SET `detail` = '[<font class=bodyhighlight>DATE</font>] Date payment is due.<br>[<font class=bodyhighlight>CLIENTNAME</font>] <br>[<font class=bodyhighlight>CLIENTEMAIL</font>] <br>[<font class=bodyhighlight>AMOUNT</font>] The total price due.<br>[<font class=bodyhighlight>CLIENTAPPLICATIONURL</font>] URL to ClientExec.<br>[<font class=bodyhighlight>FORGOTPASSWORDURL</font>] URL to retrieve forgotten password.<BR>[<font class=bodyhighlight>COMPANYNAME</font>] <BR>[<font class=bodyhighlight>COMPANYADDRESS</font>] <BR>[<font class=bodyhighlight>BILLINGEMAIL</font>] E-mail address for billing inquiries<br>[<font class=bodyhighlight>CUSTOMPROFILE_xxxx</font>]<br>where xxx is custom profile field name' WHERE `title`='Batch Invoice Notifier Tags';
UPDATE `help` SET `detail` = '[<font class=bodyhighlight>CLIENTNAME</font>]<br> Includes name and last name<br>[<font class=bodyhighlight>FIRSTNAME</font>]<br> First name of the client<br>[<font class=bodyhighlight>LASTNAME</font>]<br> Last name of the client<br>[<font class=bodyhighlight>ORGANIZATION</font>]<br> Client\'s Organization<br>[<font class=bodyhighlight>DATE</font>]<br> Actual Date<br>[<font class=bodyhighlight>COMPANYNAME</font>] <br> Company name<br>[<font class=bodyhighlight>COMPANYADDRESS</font>] <br> Company address' WHERE `title`='Announcement Tags';
